### PR TITLE
Containers

### PR DESCRIPTION
**Pull request by florianbecker**
I'm not done in any case because there are too many issues and questions!

I have done a lot of things:
- Merge neargy/master
- Code quality for enclosing brackets
- Remove std::tuple_size, element
- Some small issues and code beautifier things
- Good start for magic_enum::array unit test.

So, as mentioned here:
https://github.com/Neargye/magic_enum/pull/187#issuecomment-1316742406
Please provide me with all your known use cases.

Known Bugs:
Sorting the magic_enum::array will break the integrity - so we need to make the sort unworkable or make the kind useable.
std::get will become ambiguous on msvc2019 if you use the same index and an enum_value in the same scope.

For my current work, there is an error with set.insert and emplace on msvc - others will work.

And for me, I missed some operator or function to return the std::container for comparing in that case.

We need to discuss how useful is set, bitset, and flat_set, because I do not find them helpful yet... but hopefully, with your provided cases or intention.

### CODE REVIEW

**Comment by schaumb** [comment]
Hi @florianbecker 

`Merge neargy/master` # This not required for this PR. It makes the changes opaque.
`Remove std::tuple_size, element` # This will be needed to `magic_enum::containers::array` working as `std::array`

`Code quality for enclosing brackets`
`Some small issues and code beautifier things`
`Good start for magic_enum::array unit test.`
Thanks.



Known Bugs:
`Sorting the magic_enum::array will break the integrity - so we need to make the sort unworkable or make the kind useable.` # I think this is a must have
`std::get will become ambiguous on msvc2019 if you use the same index and an enum_value in the same scope.` # I have 2 solutions for this issue:
- make a plus template parameter with default argument: `template< auto Enum, typename E, typename V, typename Index, typename X = decltype(Enum)> `
- make a `.get( )` member function as replacement


For my current work, there is an error with set.insert and emplace on msvc - others will work.
And for me, I missed some operator or function to return the std::container for comparing in that case.
We need to discuss how useful is set, bitset, and flat_set, because I do not find them helpful yet... but hopefully, with your provided cases or intention.

`Please provide me with all your known use cases.`:

The main concept is that this library `array` and `bitset` will be a drop-in replacement for the `std::array` and (constexpr) `std::bitset`, except that the `operator[]` is only works with enum values, and the template arguments are different of course.
Another template argument (indexing) is available if you want to sort the indices not by values (as `magic_enum` shrinks) but user defined sort. I developed `comparator_indexing<>` where we sort the values, and this defines the array indices. So If you use like: `array<E, comparator_indexing<name_less<>>` the first element will be the alphanumeric first enum value. 

`std::set` and `std::flat_set` concept is slightly different. Because of we know compile time the enum count, we can use `std::array` as the underlying container, and it doesn't need any allocation.
The goals:
- make constexpr containers (because in C++17 the std::set is not constexpr)
- use the  `std::set` `std::flat_set` interface
- restrict the comparator: only constexpr time usable comparator can be used.

All function must be work as same as the standard library corresponding function.

**Comment by florianbecker** [comment]
Hi @schaumb 
 
> `Merge neargy/master` # This not required for this PR. It makes the changes opaque.

Yes, but the final commit must be mergeable. Do we need to revert that? There are a lot of changes. You can solve that if you merge neargy/master into your containers...

> `Remove std::tuple_size, element` # This will be needed to `magic_enum::containers::array` working as `std::array`

This is ambiguous on macs clang compiler... is this the only way to do that? I have replaced dependencies inside to_array with stl like solution.

> Known Bugs: `Sorting the magic_enum::array will break the integrity - so we need to make the sort unworkable or make the kind useable.` # I think this is a must have

Absolutely, but that means to resort to the enum array as well, right? What about merging first and writing that known limitation in a new issue?

> `std::get will become ambiguous on msvc2019 if you use the same index and an enum_value in the same scope.` # I have 2 solutions for this issue:
> 
> * make a plus template parameter with default argument: `template< auto Enum, typename E, typename V, typename Index, typename X = decltype(Enum)> `
> * make a `.get( )` member function as replacement

Ok, I will implement this. Thank you for the possible solutions.
 
> The main concept is that this library `array` and `bitset` will be a drop-in replacement for the `std::array` and (constexpr) `std::bitset`, except that the `operator[]` is only works with enum values, and the template arguments of course. Another template argument (indexing) is available if you want to sort the indices not by values (as `magic_enum` shrinks) but user defined sort. I developed `comparator_indexing<>` where we sort the values, and this defines the array indices. So If you use like: `array<E, comparator_indexing<name_less<>>` the first element will be the alphanumeric first enum value.
> 
> `std::set` and `std::flat_set` concept is slightly different. Because of we know compile time the enum count, we can use `std::array` as the underlying container, and it doesn't need any allocation. The goals:
> 
> * make constexpr containers (because in C++17 the std::set is not constexpr)
> * use the  `std::set` `std::flat_set` interface
> * restrict the comparator: only constexpr time usable comparator can be used.
> 
> All function must be work as same as the standard library corresponding function.

Ok, thank you for your reply. I will think a little bit about it, but for tests or documentation, this is not as easy to find some meaningful checks.

**Comment by schaumb** [comment]
`std::get will become ambiguous on msvc2019 if you use the same index and an enum_value in the same scope.`

So my 1st solution not works because windows template arguments are not meet the standard. This can be solved with
- `std::get` with std::size_t are stay in std namespace, and `get` with enum need to move to ADL (`magic_enum::containers`) namespace. This cause some refactorization overhead on `std::get` with `array`
- or replace `std::size_t` template argument with `auto` too, and separate with new template argument `enable_if`-s

**Comment by florianbecker** [comment]
Okay, I have fixed that std::get issue, so the current status is a working test case for magic_enum::containers::array, and I'll go on with set and others.

**Known issues** of the array:
- Array will not persist on std::sort
- There is no operator similar to std::array

**Comment by florianbecker** [comment]
Okay, the bitset test is done. set also, but will not compile on Visual Studio 2019 and 2022, because he cannot create an Iterator to insert. I'll try to fix that but also writing some documentation now. Maybe you have a tip for a solution for that build: https://github.com/florianbecker/magic_enum/actions/runs/3536735226

**Comment by schaumb** [comment]
So, I think this self code-review comment must be solved.
https://github.com/Neargye/magic_enum/pull/187#discussion_r880911884

**Comment by florianbecker** [comment]
I have fixed the containers::set issue, but I do not have the time to fix https://github.com/Neargye/magic_enum/pull/187#discussion_r880911884.

So the status is a working containers::set test.

For containers::flat_set there are more issues for me. Constexpr will tell me something like: This will not end in a constant result. Also, begin and end may have a few issues as well - but here is also the issue with my time. I do not have an idea to fix that, nor how a flat_set is working, so this task is the earliest inspection from me in 2023.

Missing tasks are documentation work now. Maybe I have some time to finish this as well in the next few days.

To bring this merge on its way, I would suggest removing the flat_set - this is not useful for anyone currently, and writing a new issue for this. Please let me know if I should remove this for this merge.

**Comment by schaumb** [comment]
@florianbecker  It can be skipped the flat_set for this PR. You can comment out that parts of the code.
Thanks 🙏

**Comment by florianbecker** [comment]
Documentation is done, some basic examples are done, and tests are also done. flat_set is commented out.

It is useable, but I think there is a lot of work to do in near future.

Let me know, what changes have to be made by a full review from you.

**Comment by schaumb** [comment]
I don't have time to review the code here. I merge this, and we can continue the review in Neargye repo

**Pull request merged**
